---
# Group 53, Melbourne, Perth, Uttar Pradesh
# Team Members: Aditi Basu 1178282, Kevin Van 995203, Linan Jia 806003, Nand Lal Mishra 1245159, Zhirui Liang 1255971

# Common vars
availability_zone: melbourne-qh2-uom

# Volumes
volumes:
  - vol_name: cluster-1-1
    vol_size: 10
  - vol_name: cluster-1-2
    vol_size: 10
  - vol_name: cluster-2-1
    vol_size: 10
  - vol_name: cluster-2-2
    vol_size: 10
  - vol_name: cluster-3-1
    vol_size: 10
  - vol_name: cluster-3-2
    vol_size: 10

# Security groups
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  - name: couchdb-nodes
    description: "Security group for couchdb node communication"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9110
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb-erlang
    description: "Scurity group for couchdb-erlang"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_api
    description: "Security group for couchdb-HTTP-API"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0

# Instances
instances:
  - name: cluster-1
    volumes: ['cluster-1-1', 'cluster-1-2']
  - name: cluster-2
    volumes: ['cluster-2-1', 'cluster-2-2']
  - name: cluster-3
    volumes: ['cluster-3-1', 'cluster-3-2']

# Rest of necessary information
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: ubuntu
instance_flavor: uom.mse.2c9g
hosts_inventory_file: ./inventory/hosts.ini