---
# Group 53, Melbourne, Perth, Uttar Pradesh
# Team Members: Aditi Basu 1178282, Kevin Van 995203, Linan Jia 806003, Nand Lal Mishra 1245159, Zhirui Liang 1255971

# Setup of created host machines
- hosts: all
  vars_files:
    - host_vars/applications.yaml
  gather_facts: true
  roles:
    - role: configure_instances
    - role: setup_docker

# Install database on cluster
- hosts: dbcluster
  vars_files:
    - host_vars/couchdb.yaml
    - host_vars/applications.yaml
  gather_facts: true
  roles:
    - role: install_db

# Setup database cluster
- hosts: masternode
  vars_files:
    - host_vars/couchdb.yaml
    - host_vars/applications.yaml
  gather_facts: true
  roles:
    - role: setup_dbcluster

- hosts: harvesters
  vars_files:
   - host_vars/applications.yaml
  gather_facts: true
  roles:
   - role: harvester

- hosts: frontend
  vars_files:
    - host_vars/frontend.yaml
    - host_vars/applications.yaml
  gather_facts: true
  roles:
    - role: frontend
